In [ ]:
# Importing Libraries
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix



In [ ]:
# Importing Dataset
#iris = datasets.load_iris()
data = pd.read_csv("/content/Iris.csv")   

In [ ]:
# Display size of dataset
data.shape

(150, 6)

In [ ]:
# Display top rows
data.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            NaN           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
#Finding the missing values
data.isnull().sum()

Id               0
SepalLengthCm    1
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [ ]:
#drop miss val
data.dropna(inplace=True)
data.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [ ]:
data.head()

In [ ]:
# Encoding the data
lbl = LabelEncoder()
data["Species"] =lbl.fit_transform(data["Species"])

In [ ]:
data.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
1   2            4.9           3.0            1.4           0.2        0
2   3            4.7           3.2            1.3           0.2        0
3   4            4.6           3.1            1.5           0.2        0
4   5            5.0           3.6            1.4           0.2        0
5   6            5.4           3.9            1.7           0.4        0

In [ ]:
# Identify Dependent and Independent variable
x = data.iloc[:,1:5].values
y = data.iloc[:,-1].values

In [ ]:
# Another strategy for handling missing val
imputer = SimpleImputer(missing_values = np.nan , strategy = 'mean',)
imputer = imputer.fit(x[:,:])
x[:,:] = imputer.transform(x[:,:])

In [ ]:
x[0]

In [ ]:
# split dataset into train and test
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3, random_state=32)

In [ ]:
# Intializing the algorithm
cls = DecisionTreeClassifier()
#cls = LogisticRegression()

In [ ]:
# Training of Algorithm
cls = cls.fit(x_train,y_train)

In [ ]:
# testing of result
y_pred = cls.predict(x_test)

In [ ]:
# Print val
y_pred

array([1, 0, 0, 1, 2, 2, 0, 0, 1, 0, 2, 2, 1, 1, 2, 2, 1, 2, 2, 0, 0, 2,
       2, 0, 0, 1, 0, 2, 0, 0, 1, 0, 0, 2, 1, 0, 0, 2, 2, 1, 0, 2, 0, 2,
       0])

In [ ]:
# print actual values
y_test

array([1, 0, 0, 1, 2, 2, 0, 0, 1, 0, 1, 2, 1, 1, 2, 2, 1, 2, 1, 0, 0, 2,
       2, 0, 0, 1, 0, 2, 0, 0, 1, 0, 0, 2, 1, 0, 0, 2, 2, 1, 0, 2, 0, 2,
       0])

In [ ]:
# Performance Evaluation
confusion_matrix(y_test, y_pred)

array([[19,  0,  0],
       [ 0, 10,  2],
       [ 0,  0, 14]])

In [ ]:
# Performance Evaluation
print("Accuracy:",accuracy_score(y_test, y_pred))

Accuracy: 0.9555555555555556
